name = "Example Modpack"
author = "Team Atelier"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "999fab3235f829024495f855b965cf9961df2dac41310b014a5b96f5c5f79113"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
