name = "Create Alchemy Workshop"
author = "Team Atelier"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "581dca89ecd108196d10bca6c6db6b7070b7be4541823227aa8dd6c6b2eac23b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
